name: "${name}"
main: ru.sliva.vanish.Vanish
version: "${version}"
description: "${description}"
api-version: 1.19
author: sliva_ru
commands:
  vanish:
    description: 'Main command.'
    usage: '/vanish'
    aliases: [v]
    permission: 'vanish.command']
